### ISSUE TITLE
Failed to find a verifier: null

### ISSUE THREAD

**Issue by taruntrehan** [foreseecode/acs-apiclient-java#17]
Hi Team,

I am getting an error in the following method of AcsApiClient.
Method Name : getVerifierFromRedirect
Generic exception is caught message shows null.
log message : Failed to find a verifier: null
This call was working perfectly recently but started failing even though nothing changed in any of our environments.
Please suggest.

**Comment by battewr** [comment]
Problem is result of expired password.  I am opening up a feature request to make it more obvious what is wrong in this scenario.

**Comment by taruntrehan** [comment]
Agreed, the issue happens due to expired password. Just to add that you get a response redirect to  some "index.jsp". Watch out for this till a correct error code notification comes in place. Further, foresee has a password expiry of 3 months; so monitor/update your API user's passwords accordingly.
